---
language: python
python: "2.7"
sudo: required
dist: trusty
env:
  global:
  - secure: "obbEYAKVd6azpY9BxIJAxM2eOaqEryC1+rQlFNsK+gbXqeGvT5ACK7h3avlJIYcm7hmuvx0ix0gMmlej67Se4QxfLznbfeRWZfU3JPBJFFmylFGlfW3ZLwq7XrKlFWBpGzS7p/saO+nwJkwnK716Ua1VCwAo1tBildm/A+1T/D70EINVwLUZu5whbwKf/S6/eWPIxGPX32V5ddt3hHRsa697H4BPMONILudW+sd3/M+o+iCahaJwTiEIjqG3qtS7qw1TyyrgKT8i6ZG/J1o2CrkdKawxwZiTJUioamGSXWNgExE8VgEMbWZglTe2oZya7tdKIPAK7qGVudQSO2xlWDl90zdL08iiHnEOJNw5tXEiSBqewoRnSM5HWd0hc6KjACqiySi8VGx35qbTRKs1VwlBpD686GAZqZV64MOX9emBBm0BQ41K1A8vLzHCSZDaw62r33jf2FkWZ7XGpMthpySoZeFWgxjFFJbW1/R1RFYhU4NKAggqcs9T1c1kUV4IRDFp5noqtsaJSeHsWswxvsSOHVscPTHBvDnIuR3EvOjdF4jaoBIDr0RKvSwvdI+GH4udq6935ZAIHuBTlDR9YWvDfmkYGZZNOAdGrdQWO746gpm3QVvwJL+1kRYN/GAlUGCw4vYxC+Bw2phRCfGT2jf6FQDUVjXFOkIbtIaStek="
  - secure: "SVyAxfG/d91o/JArFHoKmbTaLzTvqaB6jFZwLGm1qJkeH5Q2LQmRFh5GISGNwvxHbLFKuZ/V95mLTuAUIZsa2mp23pzf0s4U07/LcTHXX3rxeauuPI2VQP6JZuqvprUqjbeqP17+aGF5hzQzE1hRU5Rsp02BeFQF8Alemk+MPz+WnDOxsXnMGT0lL/C61jxpnP+CJf5EjeB9pVLSTFzbw7+bZRxYWG+Leqmj9LFtV5tUlgfIGrk+mOTp9SWkZHM09OyPAAotpWO8ZBCtSmv3QKlcigyZrAv4HvATAuNoVEBDnkJM23oArKCU6fsYK3imMRyLPCCpEPCyRBXS7ueeIHdamCJMJoZIpFFn+6CbcvoX+yvXtpv5oEVXuB/nfgl2xE5cHe8BVJ9fp8KJq0EJYBVlVi4UZ2jJh8uiB0b3BfEAjOt5XOdvyQRrgO0Z0a60n7Ol0b6ZgJPSPrl5sE7AhgSvkzO4eyqQd9AV7/IQYnSVEcmpRzVT5NpFfbHyBho7YXYmD6Ss80aMh0KjKuOupA3qGS5hb5++h6EBCLTRzinAQ52pgd9/2Vre06/Ur/fOWVfiqX/aQAMSKdaB9N+cpktSyVfbboqWrZw1vJQ4zk43FUfFb6O1VHbZtKygjfDcLchijtJaL6zD356oqFX/DilFG8lKE1bntUVz5xkFfIE="
git:
  submodules: false
before_install:
 - git submodule update --init --recursive
 - git submodule foreach git pull origin master
 - sudo apt-get update -qq
 - sudo apt-get install -qq squashfs-tools uuid python-apt python-pycurl btrfs-tools
install:
 - sudo pip install ansible
 - sudo pip install docker-py
script:
- cd squashible
- sudo ansible-playbook -i hosts_generator.py squashible.yml -e "live_os=debian_8"
- ls -lah live_output
- sudo chown -R travis:travis live_output
- cd live_output
after_success:
    "curl --ftp-create-dirs -T '{vmlinuz,initrd.img,filesystem.squashfs}' -u $FTP_USER:$FTP_PASSWORD ftp://images.squashible.com/images/squashible-debian-jessie-minimal/"
